# Generated by Django 4.0.2 on 2022-02-07 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='Заголовок')),
                ('discripton', models.TextField(blank=True, default='Нет записей', null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.CharField(blank=True, choices=[(1, 'Спорт'), (2, 'Политика'), (3, 'Культура'), (4, 'Криптавалюта'), (5, 'Фильмы'), (6, 'Сериалы')], max_length=200, verbose_name='Категории')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
